// Generated by CIRCT firtool-1.150.2
module NextPC(	// src/main/scala/components/nextpc.scala:22:7
  input         io_branch,	// src/main/scala/components/nextpc.scala:23:14
  input  [1:0]  io_jumptype,	// src/main/scala/components/nextpc.scala:23:14
  input  [63:0] io_inputx,	// src/main/scala/components/nextpc.scala:23:14
                io_inputy,	// src/main/scala/components/nextpc.scala:23:14
  input  [2:0]  io_funct3,	// src/main/scala/components/nextpc.scala:23:14
  input  [63:0] io_pc,	// src/main/scala/components/nextpc.scala:23:14
                io_imm,	// src/main/scala/components/nextpc.scala:23:14
  output [63:0] io_nextpc,	// src/main/scala/components/nextpc.scala:23:14
  output        io_taken	// src/main/scala/components/nextpc.scala:23:14
);

  wire
    struct packed {logic branch; logic [1:0] jumptype; logic [63:0] inputx; logic [63:0] inputy; logic [2:0] funct3; logic [63:0] pc; logic [63:0] imm; logic [63:0] nextpc; logic taken; }
    io;	// src/main/scala/components/nextpc.scala:22:7
  wire        _GEN =
    io.funct3 == 3'h0 & io.inputx == io.inputy | io.funct3 == 3'h1
    & io.inputx != io.inputy | io.funct3 == 3'h4 & $signed(io.inputx) < $signed(io.inputy)
    | io.funct3 == 3'h5 & $signed(io.inputx) >= $signed(io.inputy) | io.funct3 == 3'h6
    & io.inputx < io.inputy | (&io.funct3) & io.inputx >= io.inputy;	// src/main/scala/components/nextpc.scala:22:7, :37:{23,36,48}, :38:{10,23,36,48}, :39:{10,23,36,55}, :40:{10,23,36,55}, :41:{10,23,36,48}, :42:{10,23,36,48}
  wire [63:0] _GEN_0 = _GEN ? io.pc + io.imm : io.pc + 64'h4;	// src/main/scala/components/nextpc.scala:22:7, :38:10, :39:10, :40:10, :41:10, :42:{10,63}, :43:{17,26}, :47:{17,26}
  wire        _GEN_1 = |io.jumptype;	// src/main/scala/components/nextpc.scala:22:7, :50:28
  wire [63:0] _io_nextpc_T_9 = io.jumptype[0] ? io.inputx + io.imm : io.pc + io.imm;	// src/main/scala/components/nextpc.scala:22:7, :51:{21,33,48}, :52:44
  wire [63:0] _GEN_2 = _GEN_1 ? _io_nextpc_T_9 : io.pc + 64'h4;	// src/main/scala/components/nextpc.scala:22:7, :50:{28,37}, :51:{15,21}, :55:{15,24}
  wire [63:0] _GEN_3 = io.branch ? _GEN_0 : _GEN_2;	// src/main/scala/components/nextpc.scala:22:7, :36:20, :42:63, :43:17, :47:17, :50:37, :51:15, :55:15
  wire        _GEN_4 = io.branch ? _GEN : _GEN_1;	// src/main/scala/components/nextpc.scala:22:7, :36:20, :38:10, :39:10, :40:10, :41:10, :42:{10,63}, :50:{28,37}
  assign io =
    '{branch: io_branch,
      jumptype: io_jumptype,
      inputx: io_inputx,
      inputy: io_inputy,
      funct3: io_funct3,
      pc: io_pc,
      imm: io_imm,
      nextpc: _GEN_3,
      taken: _GEN_4};	// src/main/scala/components/nextpc.scala:22:7, :36:20, :42:63, :50:37
  assign io_nextpc = io.nextpc;	// src/main/scala/components/nextpc.scala:22:7
  assign io_taken = io.taken;	// src/main/scala/components/nextpc.scala:22:7
endmodule

