// Generated by CIRCT firtool-1.150.2
module RegisterFile(	// src/main/scala/components/register-file.scala:37:7
  input         clock,	// src/main/scala/components/register-file.scala:37:7
  input  [4:0]  io_readreg1,	// src/main/scala/components/register-file.scala:38:14
                io_readreg2,	// src/main/scala/components/register-file.scala:38:14
                io_writereg,	// src/main/scala/components/register-file.scala:38:14
  input  [63:0] io_writedata,	// src/main/scala/components/register-file.scala:38:14
  input         io_wen,	// src/main/scala/components/register-file.scala:38:14
  output [63:0] io_readdata1,	// src/main/scala/components/register-file.scala:38:14
                io_readdata2	// src/main/scala/components/register-file.scala:38:14
);

  wire
    struct packed {logic [4:0] readreg1; logic [4:0] readreg2; logic [4:0] writereg; logic [63:0] writedata; logic wen; logic [63:0] readdata1; logic [63:0] readdata2; }
    io;	// src/main/scala/components/register-file.scala:37:7
  reg  [31:0][63:0] regs;	// src/main/scala/components/register-file.scala:53:17
  assign io =
    '{readreg1: io_readreg1,
      readreg2: io_readreg2,
      writereg: io_writereg,
      writedata: io_writedata,
      wen: io_wen,
      readdata1: regs[io.readreg1],
      readdata2: regs[io.readreg2]};	// src/main/scala/components/register-file.scala:37:7, :53:17, :62:16, :63:16
  always @(posedge clock) begin	// src/main/scala/components/register-file.scala:37:7
    if (io.wen)	// src/main/scala/components/register-file.scala:37:7
      regs[io.writereg] <= io.writedata;	// src/main/scala/components/register-file.scala:37:7, :53:17
  end // always @(posedge)
  assign io_readdata1 = io.readdata1;	// src/main/scala/components/register-file.scala:37:7
  assign io_readdata2 = io.readdata2;	// src/main/scala/components/register-file.scala:37:7
endmodule

