// Generated by CIRCT firtool-1.150.2
module SingleCycleCPU(	// src/main/scala/dino.scala:152:7
  input         clock,	// src/main/scala/dino.scala:152:7
                reset,	// src/main/scala/dino.scala:152:7
  output [63:0] io_imem_address,	// src/main/scala/dino.scala:18:14
  output        io_imem_valid,	// src/main/scala/dino.scala:18:14
  input         io_imem_good,	// src/main/scala/dino.scala:18:14
  input  [63:0] io_imem_instruction,	// src/main/scala/dino.scala:18:14
  input         io_imem_ready,	// src/main/scala/dino.scala:18:14
  output [63:0] io_dmem_address,	// src/main/scala/dino.scala:18:14
  output        io_dmem_valid,	// src/main/scala/dino.scala:18:14
  input         io_dmem_good,	// src/main/scala/dino.scala:18:14
  output [63:0] io_dmem_writedata,	// src/main/scala/dino.scala:18:14
  output        io_dmem_memread,	// src/main/scala/dino.scala:18:14
                io_dmem_memwrite,	// src/main/scala/dino.scala:18:14
  output [1:0]  io_dmem_maskmode,	// src/main/scala/dino.scala:18:14
  output        io_dmem_sext,	// src/main/scala/dino.scala:18:14
  input  [63:0] io_dmem_readdata	// src/main/scala/dino.scala:18:14
);

  wire [63:0] _nextpc_io_nextpc;	// src/main/scala/dino.scala:160:26
  wire [63:0] _immGen_io_sextImm;	// src/main/scala/dino.scala:159:26
  wire [63:0] _alu_io_result;	// src/main/scala/dino.scala:158:26
  wire [4:0]  _aluControl_io_operation;	// src/main/scala/dino.scala:157:26
  wire [63:0] _registers_io_readdata1;	// src/main/scala/dino.scala:156:26
  wire [63:0] _registers_io_readdata2;	// src/main/scala/dino.scala:156:26
  wire        _control_io_itype;	// src/main/scala/dino.scala:155:26
  wire        _control_io_aluop;	// src/main/scala/dino.scala:155:26
  wire        _control_io_src1;	// src/main/scala/dino.scala:155:26
  wire [1:0]  _control_io_src2;	// src/main/scala/dino.scala:155:26
  wire        _control_io_branch;	// src/main/scala/dino.scala:155:26
  wire [1:0]  _control_io_jumptype;	// src/main/scala/dino.scala:155:26
  wire        _control_io_resultselect;	// src/main/scala/dino.scala:155:26
  wire [1:0]  _control_io_memop;	// src/main/scala/dino.scala:155:26
  wire        _control_io_toreg;	// src/main/scala/dino.scala:155:26
  wire        _control_io_regwrite;	// src/main/scala/dino.scala:155:26
  wire        _control_io_wordinst;	// src/main/scala/dino.scala:155:26
  wire
    struct packed {struct packed {logic [63:0] address; logic valid; logic good; logic [63:0] instruction; logic ready; } imem; struct packed {logic [63:0] address; logic valid; logic good; logic [63:0] writedata; logic memread; logic memwrite; logic [1:0] maskmode; logic sext; logic [63:0] readdata; } dmem; }
    io;	// src/main/scala/dino.scala:152:7
  reg  [63:0] pc;	// src/main/scala/dino.scala:154:37
  reg  [29:0] cycleCount;	// src/main/scala/chisel3/util/Counter.scala:61:40
  wire        cycleCount_wrap_wrap = &cycleCount;	// src/main/scala/chisel3/util/Counter.scala:61:40, :73:24
  wire        cycleCount_wrap = cycleCount_wrap_wrap;	// src/main/scala/chisel3/util/Counter.scala:73:24, :117:24
  wire
    struct packed {logic [63:0] address; logic valid; logic good; logic [63:0] instruction; logic ready; }
    _GEN =
    '{address: pc,
      valid: (1'h1),
      good: io_imem_good,
      instruction: io_imem_instruction,
      ready: io_imem_ready};	// src/main/scala/dino.scala:152:7, :154:37, :164:19, :165:17
  wire [31:0] instruction =
    pc[2:0] == 3'h4 ? io.imem.instruction[63:32] : io.imem.instruction[31:0];	// src/main/scala/dino.scala:152:7, :154:37, :167:25, :168:{13,20,29}, :169:{17,39}, :171:{17,39}
  wire [2:0]  funct3 = instruction[14:12];	// src/main/scala/dino.scala:167:25, :173:27
  wire [63:0] _registers_io_writedata_T =
    _control_io_resultselect ? _immGen_io_sextImm : _alu_io_result;	// src/main/scala/dino.scala:155:26, :158:26, :159:26, :180:72
  wire [63:0] _registers_io_writedata_T_1 =
    _control_io_toreg ? io.dmem.readdata : _registers_io_writedata_T;	// src/main/scala/dino.scala:152:7, :155:26, :180:{32,72}
  wire        isNegativeAddi =
    instruction[6:0] == 7'h13 & funct3 == 3'h0 & _immGen_io_sextImm[63];	// src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/dino.scala:159:26, :167:25, :173:27, :175:35, :203:{42,59,69,82,102}
  wire [63:0] buggyImmediate = _immGen_io_sextImm - {63'h0, isNegativeAddi};	// src/main/scala/dino.scala:159:26, :203:82, :204:42
  wire [63:0] _alu_io_inputx_T = _control_io_src1 ? pc : _registers_io_readdata1;	// src/main/scala/dino.scala:154:37, :155:26, :156:26, :207:23
  wire [63:0] _alu_io_inputy_T_4 =
    _control_io_src2 == 2'h1 ? buggyImmediate : {61'h0, _control_io_src2 == 2'h2, 2'h0};	// src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/dino.scala:155:26, :204:42, :209:56, :210:56
  wire [63:0] _alu_io_inputy_T_5 =
    _control_io_src2 == 2'h0 ? _registers_io_readdata2 : _alu_io_inputy_T_4;	// src/main/scala/chisel3/util/Mux.scala:130:16, src/main/scala/dino.scala:155:26, :156:26, :208:56
  wire
    struct packed {logic [63:0] address; logic valid; logic good; logic [63:0] writedata; logic memread; logic memwrite; logic [1:0] maskmode; logic sext; logic [63:0] readdata; }
    _GEN_0 =
    '{address: _alu_io_result,
      valid: (_control_io_memop[1]),
      good: io_dmem_good,
      writedata: _registers_io_readdata2,
      memread: (~(_control_io_memop[0])),
      memwrite: (_control_io_memop[0]),
      maskmode: (funct3[1:0]),
      sext: (~(funct3[2])),
      readdata: io_dmem_readdata};	// src/main/scala/dino.scala:152:7, :155:26, :156:26, :158:26, :173:27, :212:19, :213:{19,22,39}, :214:20, :215:{17,36}, :216:{20,29}, :217:{16,19,26}, :218:21
  assign io = '{imem: _GEN, dmem: _GEN_0};	// src/main/scala/dino.scala:152:7, :164:19, :165:17, :212:19, :213:19, :214:20, :215:17, :216:20, :217:16, :218:21
  always @(posedge clock) begin	// src/main/scala/dino.scala:152:7
    if (reset)	// src/main/scala/dino.scala:152:7
      pc <= 64'h0;	// src/main/scala/dino.scala:154:37
    else	// src/main/scala/dino.scala:152:7
      pc <= _nextpc_io_nextpc;	// src/main/scala/dino.scala:154:37, :160:26
  end // always @(posedge)
  always @(posedge clock) begin	// src/main/scala/dino.scala:152:7
    if (reset)	// src/main/scala/dino.scala:152:7
      cycleCount <= 30'h0;	// src/main/scala/chisel3/util/Counter.scala:61:40
    else	// src/main/scala/dino.scala:152:7
      cycleCount <= cycleCount + 30'h1;	// src/main/scala/chisel3/util/Counter.scala:61:40, :77:24
  end // always @(posedge)
  Control control (	// src/main/scala/dino.scala:155:26
    .io_opcode       (instruction[6:0]),	// src/main/scala/dino.scala:167:25, :175:35
    .io_itype        (_control_io_itype),
    .io_aluop        (_control_io_aluop),
    .io_src1         (_control_io_src1),
    .io_src2         (_control_io_src2),
    .io_branch       (_control_io_branch),
    .io_jumptype     (_control_io_jumptype),
    .io_resultselect (_control_io_resultselect),
    .io_memop        (_control_io_memop),
    .io_toreg        (_control_io_toreg),
    .io_regwrite     (_control_io_regwrite),
    .io_validinst    (/* unused */),
    .io_wordinst     (_control_io_wordinst)
  );	// src/main/scala/dino.scala:155:26
  RegisterFile registers (	// src/main/scala/dino.scala:156:26
    .clock        (clock),
    .io_readreg1  (instruction[19:15]),	// src/main/scala/dino.scala:167:25, :177:39
    .io_readreg2  (instruction[24:20]),	// src/main/scala/dino.scala:167:25, :178:39
    .io_writereg  (instruction[11:7]),	// src/main/scala/dino.scala:167:25, :179:39
    .io_writedata (_registers_io_writedata_T_1),	// src/main/scala/dino.scala:180:32
    .io_wen       ((|(instruction[11:7])) & _control_io_regwrite),	// src/main/scala/dino.scala:155:26, :167:25, :179:39, :181:{31,39}
    .io_readdata1 (_registers_io_readdata1),
    .io_readdata2 (_registers_io_readdata2)
  );	// src/main/scala/dino.scala:156:26
  ALUControl aluControl (	// src/main/scala/dino.scala:157:26
    .io_aluop     (_control_io_aluop),	// src/main/scala/dino.scala:155:26
    .io_itype     (_control_io_itype),	// src/main/scala/dino.scala:155:26
    .io_funct7    (instruction[31:25]),	// src/main/scala/dino.scala:167:25, :199:38
    .io_funct3    (funct3),	// src/main/scala/dino.scala:173:27
    .io_wordinst  (_control_io_wordinst),	// src/main/scala/dino.scala:155:26
    .io_operation (_aluControl_io_operation)
  );	// src/main/scala/dino.scala:157:26
  ALU alu (	// src/main/scala/dino.scala:158:26
    .io_operation (_aluControl_io_operation),	// src/main/scala/dino.scala:157:26
    .io_inputx    (_alu_io_inputx_T),	// src/main/scala/dino.scala:207:23
    .io_inputy    (_alu_io_inputy_T_5),	// src/main/scala/chisel3/util/Mux.scala:130:16
    .io_result    (_alu_io_result)
  );	// src/main/scala/dino.scala:158:26
  ImmediateGenerator immGen (	// src/main/scala/dino.scala:159:26
    .io_instruction ({32'h0, instruction}),	// src/main/scala/dino.scala:167:25, :187:25
    .io_sextImm     (_immGen_io_sextImm)
  );	// src/main/scala/dino.scala:159:26
  NextPC nextpc (	// src/main/scala/dino.scala:160:26
    .io_branch   (_control_io_branch),	// src/main/scala/dino.scala:155:26
    .io_jumptype (_control_io_jumptype),	// src/main/scala/dino.scala:155:26
    .io_inputx   (_registers_io_readdata1),	// src/main/scala/dino.scala:156:26
    .io_inputy   (_alu_io_inputy_T_5),	// src/main/scala/chisel3/util/Mux.scala:130:16
    .io_funct3   (funct3),	// src/main/scala/dino.scala:173:27
    .io_pc       (pc),	// src/main/scala/dino.scala:154:37
    .io_imm      (_immGen_io_sextImm),	// src/main/scala/dino.scala:159:26
    .io_nextpc   (_nextpc_io_nextpc),
    .io_taken    (/* unused */)
  );	// src/main/scala/dino.scala:160:26
  assign io_imem_address = io.imem.address;	// src/main/scala/dino.scala:152:7
  assign io_imem_valid = 1'h1;	// src/main/scala/dino.scala:152:7
  assign io_dmem_address = io.dmem.address;	// src/main/scala/dino.scala:152:7
  assign io_dmem_valid = io.dmem.valid;	// src/main/scala/dino.scala:152:7
  assign io_dmem_writedata = io.dmem.writedata;	// src/main/scala/dino.scala:152:7
  assign io_dmem_memread = io.dmem.memread;	// src/main/scala/dino.scala:152:7
  assign io_dmem_memwrite = io.dmem.memwrite;	// src/main/scala/dino.scala:152:7
  assign io_dmem_maskmode = io.dmem.maskmode;	// src/main/scala/dino.scala:152:7
  assign io_dmem_sext = io.dmem.sext;	// src/main/scala/dino.scala:152:7
endmodule

